package com.tma.project.entities;
// Generated Oct 4, 2017 3:18:35 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public")
public class Product implements java.io.Serializable {
	
	private UUID productId;
	private Integer item;
	private String class_;
	private String inventory;
	private Set<Sales> saleses = new HashSet<Sales>(0);

	public Product() {
	}

	public Product(UUID productId) {
		this.productId = productId;
	}

	public Product(UUID productId, Integer item, String class_, String inventory, Set<Sales> saleses) {
		this.productId = productId;
		this.item = item;
		this.class_ = class_;
		this.inventory = inventory;
		this.saleses = saleses;
	}

	@Id

	@Column(name = "product_id", unique = true, nullable = false)
	public UUID getProductId() {
		return this.productId;
	}

	public void setProductId(UUID productId) {
		this.productId = productId;
	}

	@Column(name = "item")
	public Integer getItem() {
		return this.item;
	}

	public void setItem(Integer item) {
		this.item = item;
	}

	@Column(name = "class", length = 0)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "inventory", length = 0)
	public String getInventory() {
		return this.inventory;
	}

	public void setInventory(String inventory) {
		this.inventory = inventory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Sales> getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set<Sales> saleses) {
		this.saleses = saleses;
	}

}
