package com.tma.project.entities;
// Generated Oct 4, 2017 3:18:35 PM by Hibernate Tools 5.2.5.Final

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * SalesId generated by hbm2java
 */
@Embeddable
public class SalesId implements java.io.Serializable {
	private UUID productId;
	private UUID timeId;
	private UUID locationId;

	public SalesId() {
	}

	public SalesId(UUID productId, UUID timeId, UUID locationId) {
		this.productId = productId;
		this.timeId = timeId;
		this.locationId = locationId;
	}
	
	@Column(name = "product_id", nullable = false)
	public UUID getProductId() {
		return this.productId;
	}

	public void setProductId(UUID productId) {
		this.productId = productId;
	}
	
	@Column(name = "time_id", nullable = false)
	public UUID getTimeId() {
		return this.timeId;
	}

	public void setTimeId(UUID timeId) {
		this.timeId = timeId;
	}
	
	@Column(name = "location_id", nullable = false)
	public UUID getLocationId() {
		return this.locationId;
	}

	public void setLocationId(UUID locationId) {
		this.locationId = locationId;
	}

//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof SalesId))
//			return false;
//		SalesId castOther = (SalesId) other;
//
//		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
//				&& castOther.getProductId() != null && Arrays.equals(this.getProductId(), castOther.getProductId())))
//				&& ((this.getTimeId() == castOther.getTimeId()) || (this.getTimeId() != null
//						&& castOther.getTimeId() != null && this.getTimeId().equals(castOther.getTimeId())))
//				&& ((this.getLocationId() == castOther.getLocationId())
//						|| (this.getLocationId() != null && castOther.getLocationId() != null
//								&& Arrays.equals(this.getLocationId(), castOther.getLocationId())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (getProductId() == null ? 0 : Arrays.hashCode(this.getProductId()));
//		result = 37 * result + (getTimeId() == null ? 0 : this.getTimeId().hashCode());
//		result = 37 * result + (getLocationId() == null ? 0 : Arrays.hashCode(this.getLocationId()));
//		return result;
//	}

}
