package com.tma.project.entities;
// Generated Oct 4, 2017 3:18:35 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Time generated by hbm2java
 */
@Entity
@Table(name = "time", schema = "public")
public class Time implements java.io.Serializable {

	private UUID timeId;
	private Integer month;
	private Integer quarter;
	private Integer year;
	private Set<Sales> saleses = new HashSet<Sales>(0);

	public Time() {
	}

	public Time(UUID timeId) {
		this.timeId = timeId;
	}

	public Time(UUID timeId, Integer month, Integer quarter, Integer year, Set<Sales> saleses) {
		this.timeId = timeId;
		this.month = month;
		this.quarter = quarter;
		this.year = year;
		this.saleses = saleses;
	}

	@Id

	@Column(name = "time_id", unique = true, nullable = false)
	public UUID getTimeId() {
		return this.timeId;
	}

	public void setTimeId(UUID timeId) {
		this.timeId = timeId;
	}

	@Column(name = "month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "quarter")
	public Integer getQuarter() {
		return this.quarter;
	}

	public void setQuarter(Integer quarter) {
		this.quarter = quarter;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "time")
	public Set<Sales> getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set<Sales> saleses) {
		this.saleses = saleses;
	}

}
